package ui.manager;

import database.DatabaseConnectionHandler;
import model.employees.Employee;

public class HotelManagerUI extends javax.swing.JFrame {
    private javax.swing.JButton displayRoomButton;
    private javax.swing.JButton displayEmpButton;

    private Employee manager;
    private DatabaseConnectionHandler dbHandler;

    public HotelManagerUI(Employee manager, DatabaseConnectionHandler dbHandler) {
        this.manager = manager;
        this.dbHandler = dbHandler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayEmpButton = new javax.swing.JButton();
        displayRoomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayEmpButton.setText("Display Cleaners");
        displayEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayEmpButtonActionPerformed(evt);
            }
        });

        displayRoomButton.setText("Display Analytics");
        displayRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(displayEmpButton)
                .addGap(29, 29, 29)
                .addComponent(displayRoomButton)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayEmpButton)
                    .addComponent(displayRoomButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.EventQueue.invokeLater(() -> new DisplayCleaners(dbHandler.getCleanersForHotel(manager.getHotelID())).setVisible(true));
    }

    private void displayRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.EventQueue.invokeLater(() -> new DisplayRooms(dbHandler.getRoomsForHotel(manager.getHotelID())).setVisible(true));
    }

}
